// <auto-generated />
using System;
using MbCore.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MbCore.EntityFramework.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MbCore.EntityFramework.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Experience");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Experience");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MbCore.EntityFramework.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("MbCore.EntityFramework.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("MbCore.EntityFramework.Models.PersonalProject", b =>
                {
                    b.HasBaseType("MbCore.EntityFramework.Models.Experience");

                    b.HasDiscriminator().HasValue("PersonalProject");
                });

            modelBuilder.Entity("MbCore.EntityFramework.Models.WorkExperience", b =>
                {
                    b.HasBaseType("MbCore.EntityFramework.Models.Experience");

                    b.Property<bool>("CurrentPosition")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Position")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasDiscriminator().HasValue("WorkExperience");
                });

            modelBuilder.Entity("MbCore.EntityFramework.Models.Tag", b =>
                {
                    b.HasOne("MbCore.EntityFramework.Models.Experience", "Experience")
                        .WithMany("Tags")
                        .HasForeignKey("ExperienceId");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("MbCore.EntityFramework.Models.Experience", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
